version: '3'
services:
  flow:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NO_CACHE=1
    image: flowise:flow
    container_name: flow_container
    ports:
      - "8060:8080"